#! /bin/sh

sxhkd &

bspc monitor -d WWW PDF UEB PDF MAIL MISC

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Emacs desktop='^1'
bspc rule -a Vim state=floating
bspc rule -a zathura state=floating

$HOME/.config/polybar/launch.sh
nm-applet
compton -b
